baseURL = 'https://afis.nz/'
languageCode = 'en-nz'
title = 'Auckland French International School'
author = 'AFIS'

defaultContentLanguage = "en"
enableRobotsTXT = true

[languages]
[languages.en]
title = "Auckland French International School"
weight = 1
contentDir = "content/en"
[languages.en.params]
flag = "🇳🇿"

[languages.fr]
title = "École Française Internationale d'Auckland"
weight = 2
contentDir = "content/fr"
[languages.fr.params]
flag = "🇫🇷"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
logo = "/images/afis-logo4.png"
description = "Auckland French International School Description"
copyrightYears = 2024
themeColor = "blue"
bannerHeight = "200px"

[social]
twitter = "afauckland"
